# Generated by Django 5.2.8 on 2025-11-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username_alter_user_email'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('roll_number__isnull', False)), fields=('roll_number',), name='unique_roll_number_not_null'),
        ),
    ]
