# Generated by Django 5.2.8 on 2025-11-10 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('report_type', models.CharField(choices=[('individual', 'Individual'), ('class', 'Class'), ('subject', 'Subject')], max_length=20)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('processing', 'Processing'), ('downloaded', 'Downloaded'), ('failed', 'Failed')], default='generated', max_length=20)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='attendance_reports/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('class_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classsubject')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
